<div class="row">
    <ol class="breadcrumb">
        <li ng-repeat="bc in breadcrumbs" ng-hide="!bc.path">
            <a ng-href="#{{bc.path}}">
                {{bc.label}}
            </a>
        </li>
    </ol>
</div>
<br>
<span us-spinner="{radius:30, width:8, length: 16}"></span>
<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="row">
            <div class="col-md-12">
                <img src="{{ book.book_cover }}" alt="">
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="row">
            <div class="col-md-12">
                <b>Title:</b> {{ book.title }}
            </div>
            <br><br><br>
            <div class="col-md-12">
                <b>Author:</b> {{ book.author }}
            </div>
            <br><br><br>
            <div class="col-md-12">
                <b>Description:</b> {{ book.description }}
            </div>
            <br><br><br>
            <div class="col-md-12">
                <b>Year of public:</b> {{ book.public_year }}
            </div>
        </div>
    </div>
</div>